# Generated by Django 2.1.7 on 2019-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_complete',
            field=models.CharField(blank=True, default=False, max_length=5),
        ),
    ]
