# Generated by Django 2.1.7 on 2019-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_complete',
            field=models.CharField(blank=True, default=True, max_length=3),
        ),
    ]
