# Generated by Django 2.1.7 on 2019-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_auto_20190222_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_complete',
            field=models.CharField(blank=True, default=True, max_length=5),
        ),
    ]
